### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [nmaxcom/nmaxcom-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) but prefer to add themes with screenshots so users can see what a theme looks like without having to install it.

**Comment by nmaxcom** [comment]
You're absolutely right. I had it pending and the it slipped my mind, I'll do it right away.

Thanks for the reminder :)

**Comment by nmaxcom** [comment]
There it is, let me know how you like it.

**Comment by unixorn** [comment]
Added as of https://github.com/unixorn/awesome-zsh-plugins/pull/345

**Comment by nmaxcom** [comment]
I'm honored! Thanks :)
